IntelliTectWeb/Models/Person.cs
using System.ComponentModel.DataAnnotations;

namespace IntelliTectWeb.Models
{
    public class Person
    {
        public int PersonId { get; set; }

        [Required,Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required, Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Initial")]
        [StringLength(1, ErrorMessage = "Please specify middle initial only")]
        public string MiddleInitial { get; set; }

        [Required, Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [Required, Display(Name = "Email Address")]
        [EmailAddress(ErrorMessage = "Email is invalid")]
        public string EmailAddress { get; set; }
    }
}

IntelliTectWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace IntelliTectWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "IntelliTect Technical Challenge Project";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Derek Howard";

            return View();
        }

        public IActionResult Error()
        {
            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

IntelliTectWeb/Controllers/PersonController.cs
using IntelliTectWeb.Models;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Storage;
using Microsoft.Framework.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IntelliTectWeb.Data;
using IntelliTectWeb.Repos;

namespace IntelliTectWeb.Controllers
{
    public class PersonController : Controller
    {
        [FromServices]
        public ILogger<PersonController> Logger { get; set; }

        private readonly IPersonRepo _personRepo;
     	public PersonController(IPersonRepo personRepo)
     	{
     		_personRepo = personRepo;
     	}

    public IActionResult Index()
        {
            var persons = _personRepo.GetAllPersons();
            return View(persons);
        }

        public async Task<ActionResult> Details(int id)
        {
            var person = await _personRepo.GetPersonByIdAsync(id);
            if (person == null)
            {
                Logger.LogInformation("Details: Item not found {0}", id);
                return HttpNotFound();
            }
            return View(person);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("FirstName", "LastName", "MiddleInitial", "PhoneNumber", "EmailAddress")] Person person)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _personRepo.InsertPersonAsync(person);
                    return RedirectToAction("Index");
                }
            }
            catch (DataStoreException)
            {
                ModelState.AddModelError(string.Empty, "Unable to save changes.");
            }
            return View(person);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var person = await _personRepo.GetPersonByIdAsync(id);
            if (person == null)
            {
                Logger.LogInformation("Edit: Person not found {0}", id);
                return HttpNotFound();
            }
                        
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Update(int id, [Bind("FirstName", "LastName", "MiddleInitial", "PhoneNumber", "EmailAddress")] Person person)
        {
            try
            {
                await _personRepo.UpdatePersonAsync(id, person);
                return RedirectToAction("Index");
            }
            catch (DataStoreException)
            {
                ModelState.AddModelError(string.Empty, "Unable to save changes.");
            }
            return View(person);
        }

        [HttpGet]
        [ActionName("Delete")]
        public async Task<ActionResult> ConfirmDelete(int id, bool? retry)
        {
            var person = await _personRepo.GetPersonByIdAsync(id);
            if (person == null)
            {
                Logger.LogInformation("Delete: Person not found {0}", id);
                return HttpNotFound();
            }
            ViewBag.Retry = retry ?? false;
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                await _personRepo.DeletePersonByIdAsync(id);
            }
            catch (DataStoreException)
            {
                return RedirectToAction("Delete", new { id = id, retry = true });
            }
            return RedirectToAction("Index");
        }
    }
}

IntelliTectWeb/Views/Home/About.cshtml
@using System.Threading.Tasks
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

IntelliTectWeb/Views/Home/Contact.cshtml
@using System.Threading.Tasks
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    10341 N Gibson Drive<br />
    Hayden, ID 83835<br />
    <abbr title="Phone">P:</abbr>
    208.419.5327
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">howardderekl@gmail.com</a>
</address>

IntelliTectWeb/Views/Home/Index.cshtml
@using System.Threading.Tasks
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <h2>Application Information</h2>
        <p>This project was a technical challenge from IntelliTect to create an ASP.Net Person CRUD example project.</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Project Created using the following concepts.</h2>
        <ul>
            <li>.Net MVC 6</li>
            <li>Local SQL Entity Framework 7</li>
            <li>Creating using EF Context and Repository Style Adaptation</li>
            <li>Dependacy Injection used to make PersonRepository available to PersonController</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Testing</h2>
        <ul>
            <li>Testing using new Web Library Project</li>
            <li>Testing project created using xUnit</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <h2>Deployment Information</h2>
        <ul>
            <li>The bitbucket repository can be found at: <a href="https://bitbucket.org/howardderekl/intellitect" target="_new">Bitbucket Repo</a></li>
            <li>Step 1: Clone Repository <em>https://howardderekl@bitbucket.org/howardderekl/intellitect.git</em></li>
            <li>Step 2: Build Project to create dependancies</li>
            <li>Step 3: If you don't have DNVM Beta5 installed - Run the setup.bat file in the IntellitectWeb directory - Otherwise skip</li>
            <li>Step 4: Using the Visual Studio Test Explorer you can "Run All" Unit Tests (Unit Tests are still in progress)</li>
            <li>Step 5: Run the Project</li>
        </ul>
    </div>
</div>

IntelliTectWeb/Views/Person/Create.cshtml
@using System.Threading.Tasks
@model IntelliTectWeb.Models.Person

@{
    ViewBag.Title = "Create Person";
}
<h2>@ViewBag.Title</h2>
<div>
    <form asp-controller="Person" asp-action="Create" method="post">
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" placeholder="FirstName" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control" placeholder="LastName" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MiddleInitial"></label>
            <input asp-for="MiddleInitial" class="form-control" placeholder="(optional)" />
            <span asp-validation-for="MiddleInitial" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" placeholder="2085551212" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EmailAddress"></label>
            <input asp-for="EmailAddress" class="form-control" placeholder="email@address.com" />
            <span asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-default" value="Create" />
    </form>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

IntelliTectWeb/Views/Person/Delete.cshtml
@using System.Threading.Tasks
@model IntelliTectWeb.Models.Person

@{
    ViewBag.Title = "Confirm Delete";
}

<h3>Are you sure you want to delete this person?</h3>

@if (ViewBag.Retry)
{
    <p class="alert-danger">Error deleting. Retry?</p>
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleInitial)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MiddleInitial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>
    </dl>

    <div>
        <form asp-controller="Person" asp-action="Delete" method="post">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="Delete" />
            </div>
        </form>

        <p><a asp-controller="Author" asp-action="Index">Back to List</a></p>
    </div>
</div>

IntelliTectWeb/Views/Person/Details.cshtml
@using System.Threading.Tasks
@using Microsoft.Data.Entity.Metadata
@model IntelliTectWeb.Models.Person

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<div>
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.FirstName)</dt>
        <dd>@Html.DisplayFor(model => model.FirstName)</dd>

        <dt>@Html.DisplayNameFor(model => model.LastName)</dt>
        <dd>@Html.DisplayFor(model => model.LastName)</dd>

        <dt>@Html.DisplayNameFor(model => model.MiddleInitial)</dt>
        <dd>@Html.DisplayFor(model => model.MiddleInitial)</dd>

        <dt>@Html.DisplayNameFor(model => model.PhoneNumber)</dt>
        <dd>@Html.DisplayFor(model => model.PhoneNumber)</dd>

        <dt>@Html.DisplayNameFor(model => model.EmailAddress)</dt>
        <dd>@Html.DisplayFor(model => model.EmailAddress)</dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.PersonId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p> 

IntelliTectWeb/Views/Person/Edit.cshtml
@using System.Threading.Tasks
@using Microsoft.Data.Entity.Metadata
@model IntelliTectWeb.Models.Person

@{
    ViewBag.Title = "Edit Person";
}

<h2>@ViewBag.Title</h2>
<div>
    <form asp-controller="Person" asp-action="Update" method="post" asp-route-id="@Model.PersonId">
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control"/>
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="MiddleInitial"></label>
            <input asp-for="MiddleInitial" class="form-control" />
            <span asp-validation-for="MiddleInitial" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="EmailAddress"></label>
            <input asp-for="EmailAddress" class="form-control" />
            <span asp-validation-for="EmailAddress" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-default" value="Save" />
    </form>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

IntelliTectWeb/Views/Person/Index.cshtml
@using System.Threading.Tasks
@using Microsoft.Data.Entity.Metadata
@model IEnumerable<IntelliTectWeb.Models.Person>
@{
    ViewBag.Title = "People";
}
<p>
    <a asp-action="Create">Create New Person</a>
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MiddleInitial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleInitial)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PersonId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PersonId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PersonId">Delete</a>
            </td>
        </tr>
    }
</table>

IntelliTectWeb/Views/Shared/_Layout.cshtml
@using System.Threading.Tasks
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - IntelliTectWeb</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/dist/css/bootstrap-touch-carousel.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
                  asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/css/bootstrap-touch-carousel.css"
                  asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css"
                  asp-fallback-test-class="carousel-caption" asp-fallback-test-property="display" asp-fallback-test-value="none" />
            <link rel="stylesheet" href="~/css/site.css" asp-file-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">IntelliTectWeb</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Person" asp-action="Index">People</a></li>                        
                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>                        
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>
            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>
            <div class="row">
                <div class="col-md-12">&nbsp;</div>
            </div>
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2015 - Derek Howard</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/lib/hammer.js/hammer.js"></script>
            <script src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
                    asp-fallback-src="~/lib/hammer.js/hammer.js"
                    asp-fallback-test="window.Hammer">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/js/bootstrap-touch-carousel.js"
                    asp-fallback-src="~/lib/bootstrap-touch-carousel/dist/js/bootstrap-touch-carousel.js"
                    asp-fallback-test="window.Hammer && window.Hammer.Instance">
            </script>
            <script src="~/js/site.js" asp-file-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>